### ISSUE TITLE
Failed to build Docker (pip install pairing/)

### ISSUE THREAD

**Issue by hugo-tardiou** [initc3/HoneyBadgerMPC#366]
Hi,

I'm trying to run the docker with the instructions found here:
[https://github.com/initc3/HoneyBadgerMPC/blob/dev/docs/development/getting-started.rst#id3](getting-started)

Tried on both MacOS Mojave and Ubuntu 1804

Any help would be much appreciated!

Thank you,
Hugo

Commands done :

```
git clone  --branch dev https://github.com/initc3/HoneyBadgerMPC.git honeybadger
cd honeybadger
docker-compose run --rm honeybadgermpc
```
```Step 38/74 : RUN pip install pairing/
 ---> Running in 13b838244eee
Processing ./pairing
Building wheels for collected packages: pypairing
  Building wheel for pypairing (setup.py): started
  Building wheel for pypairing (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-88qt48d1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-88qt48d1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3v9ev2jg --python-tag cp37
       cwd: /tmp/pip-req-build-88qt48d1/
  Complete output (69 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/pypairing
  copying pypairing/__init__.py -> build/lib/pypairing
  running egg_info
  creating pypairing.egg-info
  writing pypairing.egg-info/PKG-INFO
  writing dependency_links to pypairing.egg-info/dependency_links.txt
  writing top-level names to pypairing.egg-info/top_level.txt
  writing manifest file 'pypairing.egg-info/SOURCES.txt'
  reading manifest file 'pypairing.egg-info/SOURCES.txt'
  writing manifest file 'pypairing.egg-info/SOURCES.txt'
  running build_ext
  running build_rust
      Updating crates.io index
   Downloading crates ...
    Downloaded aho-corasick v0.7.6
    Downloaded regex-syntax v0.6.12
    Downloaded regex v1.3.1
    Downloaded num-integer v0.1.41
    Downloaded libc v0.2.62
    Downloaded rand_core v0.3.1
    Downloaded rand v0.4.6
    Downloaded winapi v0.3.8
    Downloaded cfg-if v0.1.10
  error: failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.10/Cargo.toml`

  Caused by:
    feature `rename-dependency` is required

  consider adding `cargo-features = ["rename-dependency"]` to the manifest
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-88qt48d1/setup.py", line 54, in <module>
      cmdclass=dict(test=PyTest),
    File "/opt/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/venv/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/venv/lib/python3.7/site-packages/setuptools_rust/build_ext.py", line 26, in run
      build_rust.run()
    File "/opt/venv/lib/python3.7/site-packages/setuptools_rust/build.py", line 313, in run
      self.build_extension(ext)
    File "/opt/venv/lib/python3.7/site-packages/setuptools_rust/build.py", line 95, in build_extension
      metadata = json.loads(check_output(metadata_command).decode("utf-8"))
    File "/usr/local/lib/python3.7/subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "/usr/local/lib/python3.7/subprocess.py", line 487, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
  ----------------------------------------
  ERROR: Failed building wheel for pypairing
  Running setup.py clean for pypairing
Failed to build pypairing
Installing collected packages: pypairing
  Running setup.py install for pypairing: started
    Running setup.py install for pypairing: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /opt/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-88qt48d1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-88qt48d1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-krtz9uhv/install-record.txt --single-version-externally-managed --compile --install-headers /opt/venv/include/site/python3.7/pypairing
         cwd: /tmp/pip-req-build-88qt48d1/
    Complete output (62 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/pypairing
    copying pypairing/__init__.py -> build/lib.linux-x86_64-3.7/pypairing
    running egg_info
    writing pypairing.egg-info/PKG-INFO
    writing dependency_links to pypairing.egg-info/dependency_links.txt
    writing top-level names to pypairing.egg-info/top_level.txt
    reading manifest file 'pypairing.egg-info/SOURCES.txt'
    writing manifest file 'pypairing.egg-info/SOURCES.txt'
    running build_ext
    running build_rust
     Downloading crates ...
    error: unable to get packages from source

    Caused by:
      failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.10/Cargo.toml`

    Caused by:
      feature `rename-dependency` is required

    consider adding `cargo-features = ["rename-dependency"]` to the manifest
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-88qt48d1/setup.py", line 54, in <module>
        cmdclass=dict(test=PyTest),
      File "/opt/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/venv/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/venv/lib/python3.7/site-packages/setuptools_rust/build_ext.py", line 26, in run
        build_rust.run()
      File "/opt/venv/lib/python3.7/site-packages/setuptools_rust/build.py", line 313, in run
        self.build_extension(ext)
      File "/opt/venv/lib/python3.7/site-packages/setuptools_rust/build.py", line 95, in build_extension
        metadata = json.loads(check_output(metadata_command).decode("utf-8"))
      File "/usr/local/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/local/lib/python3.7/subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-88qt48d1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-88qt48d1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-krtz9uhv/install-record.txt --single-version-externally-managed --compile --install-headers /opt/venv/include/site/python3.7/pypairing Check the logs for full command output.
ERROR: Service 'honeybadgermpc' failed to build: The command '/bin/sh -c pip install pairing/' returned a non-zero code: 1```

**Comment by hugo-tardiou** [comment]
I believe pull request #370 fixed my issue

**Comment by sanket1729** [comment]
Yes, #370 is in now. This is fixed.
