### ISSUE TITLE
AssertionError when running samples

### ISSUE THREAD

**Issue by liorko87** [initc3/HoneyBadgerMPC#417]
Hi,

When I'm trying to run the powermixing app, using this command:
`python3 powermixing.py -d -f ../../conf/sample.json` an error raised

The error is:
```
2019-12-29 20:08:33,437:[misc.py:15]:[CRITICAL]: 
Exception: 
<Task finished coro=<Mpc._run() done, defined at /usr/src/HoneyBadgerMPC/honeybadgermpc/mpc.py:220> exception=AssertionError()> 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/HoneyBadgerMPC/honeybadgermpc/ipc.py", line 141, in callback
    program_result.set_result(future.result())
  File "/usr/src/HoneyBadgerMPC/honeybadgermpc/mpc.py", line 241, in _run
    return result.result()
  File "powermixing.py", line 17, in all_secrets_phase1
    a = context.preproc.get_rand(context)
  File "/usr/src/HoneyBadgerMPC/honeybadgermpc/preprocessing.py", line 650, in get_rand
    return self._rands.get_value(context, t)
  File "/usr/src/HoneyBadgerMPC/honeybadgermpc/preprocessing.py", line 101, in get_value
    to_return, used = self._get_value(context, key, *args, **kwargs)
  File "/usr/src/HoneyBadgerMPC/honeybadgermpc/preprocessing.py", line 413, in _get_value
    assert self.count[key] >= 1
AssertionError
)
```

What made this error arise?

**Comment by sbellem** [comment]
Thanks for reporting the issue @liorko87. We'll look into it as soon as possible.
