### ISSUE TITLE
docker setup fails

### ISSUE THREAD

**Issue by j0nas-H** [initc3/HoneyBadgerMPC#463]
Hi,
I am trying to setup my dev-environment, following [the instructions](https://github.com/initc3/HoneyBadgerMPC/blob/dev/docs/development/getting-started.rst#managing-your-development-environment-with-docker-compose) from the docs. Docker and docker-compose are installed.
Step 3 fails, with the following output.
Any tips on how to resolve this?

```
$ docker-compose run --rm honeybadgermpc

Building honeybadgermpc
Step 1/33 : ARG HBMPC_DEPS_DIGEST="46902d869ea881d7b00b72ff6accf2558a5e15849da5fa5cc722b4ff82a507f8"
Step 2/33 : FROM initc3/honeybadgermpc-deps@sha256:$HBMPC_DEPS_DIGEST AS build-compute-power-sums
 ---> 178d781e6b7f
Step 3/33 : COPY apps/asynchromix/cpp/ /usr/src/apps/asynchromix/cpp/
 ---> Using cache
 ---> 32b28e46bfa5
Step 4/33 : RUN make -C /usr/src/apps/asynchromix/cpp
 ---> Using cache
 ---> 7dd4b575c4da

Step 5/33 : FROM initc3/honeybadgermpc-deps@sha256:$HBMPC_DEPS_DIGEST AS pre-tests
 ---> 178d781e6b7f
Step 6/33 : COPY pairing /usr/src/pairing
 ---> Using cache
 ---> 90d07c4067a2
Step 7/33 : RUN pip install -v /usr/src/pairing/
 ---> Running in e30388833fa7
Created temporary directory: /tmp/pip-ephem-wheel-cache-r467fng5
Created temporary directory: /tmp/pip-req-tracker-2538l1bz
Created requirements tracker '/tmp/pip-req-tracker-2538l1bz'
Created temporary directory: /tmp/pip-install-gpypd8xh
Processing /usr/src/pairing
  Created temporary directory: /tmp/pip-req-build-3adwwbh8
  Added file:///usr/src/pairing to build tracker '/tmp/pip-req-tracker-2538l1bz'
    Running setup.py (path:/tmp/pip-req-build-3adwwbh8/setup.py) egg_info for package from file:///usr/src/pairing
    Running command python setup.py egg_info
    Collecting setuptools-rust
      Downloading https://files.pythonhosted.org/packages/82/2b/349ad916a2f032506a2c7c0810950a299f96e05d88b21797c2170bd6b2c6/setuptools_rust-0.12.1-py3-none-any.whl
    Collecting toml>=0.9.0
      Downloading https://files.pythonhosted.org/packages/44/6f/7120676b6d73228c96e17f1f794d8ab046fc910d781c8d151120c3f1569e/toml-0.10.2-py2.py3-none-any.whl
    Collecting semantic-version>=2.6.0
      Downloading https://files.pythonhosted.org/packages/a5/15/00ef3b7888a10363b7c402350eda3acf395ff05bebae312d1296e528516a/semantic_version-2.8.5-py2.py3-none-any.whl
    Collecting setuptools>=46.1
      Downloading https://files.pythonhosted.org/packages/70/e9/84e2865fddfaba4506bc5d293d2a535bf27e31b12ca16d31564f8ce28cdb/setuptools-58.5.3-py3-none-any.whl (946kB)
    Installing collected packages: toml, semantic-version, setuptools, setuptools-rust
      Found existing installation: setuptools 41.2.0
        Uninstalling setuptools-41.2.0:
          Successfully uninstalled setuptools-41.2.0
    Successfully installed semantic-version-2.8.5 setuptools-58.5.3 setuptools-rust-0.12.1 toml-0.10.2
    WARNING: You are using pip version 19.3.1; however, version 21.3.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-3adwwbh8/setup.py", line 54, in <module>
        cmdclass=dict(test=PyTest),
      File "/opt/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
      File "/opt/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        Disable finalize_options to avoid building the working set.
      File "/opt/venv/lib/python3.7/site-packages/setuptools/dist.py", line 719, in fetch_build_eggs
        "versions. Please use the underscore name '%s' instead"
      File "/opt/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
      File "/opt/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        to attempt other ways of obtaining a distribution before falling back
      File "/opt/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        """In-place addition of a distribution or environment"""
      File "/opt/venv/lib/python3.7/site-packages/setuptools/dist.py", line 761, in fetch_build_egg
        if DEBUG:
      File "/opt/venv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 52, in <module>
        from setuptools.package_index import (
      File "/opt/venv/lib/python3.7/site-packages/setuptools/package_index.py", line 30, in <module>
        from setuptools.extern.more_itertools import unique_everseen
    ModuleNotFoundError: No module named 'setuptools.extern.more_itertools'
Cleaning up...
  Removing source in /tmp/pip-req-build-3adwwbh8
Removed file:///usr/src/pairing from build tracker '/tmp/pip-req-tracker-2538l1bz'
Removed build tracker '/tmp/pip-req-tracker-2538l1bz'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/opt/venv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/opt/venv/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/opt/venv/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/opt/venv/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/opt/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "/opt/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/opt/venv/lib/python3.7/site-packages/pip/_internal/distributions/source/legacy.py", line 39, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/opt/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 563, in prepare_metadata
    self.metadata_directory = metadata_generator(self)
  File "/opt/venv/lib/python3.7/site-packages/pip/_internal/operations/generate_metadata.py", line 124, in _generate_metadata_legacy
    command_desc='python setup.py egg_info',
  File "/opt/venv/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'honeybadgermpc' failed to build : The command '/bin/sh -c pip install -v /usr/src/pairing/' returned a non-zero code: 1
```

**Comment by HTseaaat** [comment]
Hello, do you solve the problem?

**Comment by matthiasgeihs** [comment]
Having the same issue.

Maybe @sbellem can help?
